from typing import Dict, Any
from app.schemas.state import AgentState

class ReportAggregator:
    """
    Aggregates analysis results into a final report.
    """
    
    def run(self, state: AgentState) -> Dict[str, Any]:
        """
        Generates the final report based on the collected state.
        """
        consistency = state.get("consistency", {})
        grammar = state.get("grammar", {})
        novelty = state.get("novelty", {})
        fact_check = state.get("fact_check", {})
        authenticity = state.get("authenticity", {})
        
        # Calculate overall status
        statuses = [
            consistency.get("status", "Unknown"),
            grammar.get("status", "Unknown"),
            novelty.get("status", "Unknown"),
            fact_check.get("status", "Unknown"),
            authenticity.get("status", "Unknown")
        ]
        
        fail_count = statuses.count("Fail")
        if fail_count == 0:
            overall_status = "PASS"
        elif fail_count >= 3:
            overall_status = "FAIL"
        else:
            overall_status = "PARTIAL PASS"

        report = f"""# Research Paper Evaluation Report

**Executive Summary**: {overall_status}

## 📊 Detailed Scores
- **Consistency**: {consistency.get('score', 'N/A')}/100 ({consistency.get('status', 'N/A')})
- **Grammar**: {grammar.get('rating', 'N/A')} ({grammar.get('status', 'N/A')})
- **Novelty**: {novelty.get('status', 'N/A')}
- **Fact Check**: {fact_check.get('status', 'N/A')}
- **Authenticity**: {authenticity.get('score', 'N/A')}% Fabrication Probability ({authenticity.get('status', 'N/A')})

## 📝 Analysis Details

### Consistency
{consistency.get('details', 'No details available.')}

### Grammar & Tone
{grammar.get('details', 'No details available.')}

### Novelty
{novelty.get('details', 'No details available.')}

### Fact Check
{fact_check.get('details', 'No details available.')}

### Authenticity
{authenticity.get('details', 'No details available.')}

---
*Generated by Agentic Research Paper Analyzer*
"""
        return {"final_report": report}
